### ISSUE TITLE
New pack maintianer

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-cloudflare#7]
I wrote this pack some time ago and did not end up using it much, I've moved to an new employer so it's may be time to have a new maintainer?

CC: @paul-mulvihill as it's using my old `@pulsant.com` address.

**Comment by LindsayHill** [comment]
I’ve added Encore as pack maintainers

**Comment by nmaludy** [comment]
:+1: awesome, thanks!!!

**Comment by jjm** [comment]
Cool thanks @LindsayHill
